baseurl = "http://localhost/"
contentdir = "content"
languageCode = "en-us"
title = "Docker Docs"
theme = "hugo-bootswatch"


[[menu.main]]
	name = "About"
	weight = 1
[[menu.main]]
	name = "Installation"
	weight = 2
[[menu.main]]
	name = "User Guide"
	weight = 3
[[menu.main]]
	name = "Docker Hub"
	weight = 4
[[menu.main]]
	name = "Docker Hub Enterprise"
	weight = 5
[[menu.main]]
	name = "Examples"
	weight = 6
[[menu.main]]
	name = "Articles"
	weight = 7
[[menu.main]]
	name = "Reference"
	weight = 8
[[menu.main]]
	name = "Contribute"
	weight = 9
[[menu.main]]
	name = "Cloud"
	parent = "Installation"
[[menu.main]]
	name = "Linux"
	parent = "Installation"

