data:
    image: busybox
    command: "true"
    volumes:
        - /docs
        - /public

fetch:
    image: docsdockercom:${IMAGE_TAG}
    command: "./fetch_content.py /docs all-projects.yml"
    volumes_from:
        - data
    environment:
        - GITHUB_USERNAME
        - GITHUB_TOKEN
        - S3HOSTNAME

build:
    image: docsdockercom:${IMAGE_TAG}
    command: /src/build.sh
    working_dir: /docs
    volumes_from:
        - data
    environment:
        - S3HOSTNAME

upload:
    image: docsdockercom:${IMAGE_TAG}
    working_dir: /public
    command: /src/upload.sh
    volumes_from:
        - data
    environment:
        - CLEAN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_S3_BUCKET
        - S3HOSTNAME

cleanup:
    image: docsdockercom:${IMAGE_TAG}
    command: /src/cleanup.sh
    environment:
        - RM_OLDER_THAN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_S3_BUCKET

serve:
    image: docsdockercom:${IMAGE_TAG}
    working_dir: /docs
    command: "hugo server -d /public --port=8000 --baseUrl=$HUGO_BASE_URL --bind=0.0.0.0 --config=config.toml"
    ports:
        - "8000:8000"
    volumes_from:
        - data

test:
    image: docsdockercom:${IMAGE_TAG}
    working_dir: /docs
    command: '/src/docvalidate.py http://serve:8000'
    links:
        - serve
