data:
    image: busybox
    command: "true"
    volumes:
        - /docs
        - /public

fetch:
    build: .
    command: |
        /bin/bash -ec " \
        python fetch_content.py /docs all-projects.yml
        ./touch-up.sh /docs
        "
    volumes_from:
        - data
    environment:
        - GITHUB_USERNAME
        - GITHUB_TOKEN

build:
    build: .
    command: |
      /bin/bash -ec ' \
      hugo -d /public/$DOCS_VERSION
      '
    working_dir: /docs
    volumes_from:
        - data
    environment:
        - DOCS_VERSION

upload:
    build: .
    working_dir: /public
    command: |
        /bin/bash -c ' \
        sleep 1
        [ -z "$DOCS_VERSION" ]          && echo "DOCS_VERSION is not set" >&2          && exit 1
        [ -z "$AWS_ACCESS_KEY_ID" ]     && echo "AWS_ACCESS_KEY_ID is not set" >&2     && exit 1
        [ -z "$AWS_SECRET_ACCESS_KEY" ] && echo "AWS_SECRET_ACCESS_KEY is not set" >&2 && exit 1
        [ -z "$AWS_S3_BUCKET" ]         && echo "AWS_S3_BUCKET is not set" >&2         && exit 1

        aws s3 sync --exact-timestamps --delete --acl=public-read "./$DOCS_VERSION" "s3://$AWS_S3_BUCKET/$DOCS_VERSION"
        if [ -n "$LATEST" ] ; then
          rm -rf latest
          cp -R "$DOCS_VERSION" latest
          aws s3 sync --exact-timestamps --delete --acl=public-read ./latest "s3://$AWS_S3_BUCKET/latest"
        fi
        '
    volumes_from:
        - data
    environment:
        - LATEST
        - DOCS_VERSION
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_S3_BUCKET

serve:
    build: .
    working_dir: /docs
    command: /bin/bash -c "hugo server -d /public --port=8000 --baseUrl=$HUGO_BASE_URL --bind=0.0.0.0"
    environment:
        - HUGO_BASE_URL
    ports:
        - "8000:8000"
    volumes_from:
        - data

test:
    build: .
    working_dir: /docs
    command: |
        /bin/bash -c " \
        URL=http://$HUGO_BASE_URL:8000
        hugo server -d /public --port=8000 --baseUrl=$HUGO_BASE_URL --bind=$HUGO_BIND_IP & \
        until curl --fail --silent $URL ; do \
          sleep 1 ; \
        done
        exec python /src/docvalidate.py $URL
        "
    environment:
        - HUGO_BASE_URL
        - HUGO_BIND_IP
    ports:
        - "8000:8000"
    volumes_from:
        - data
